### ISSUE TITLE
WQS: PublicationTitle, issue, volume, pages for Q30000000

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/zotkat#62]
I used [Q30000000](https://www.wikidata.org/wiki/Q30000000) for looking up the structure of journal articles in Wikidata. However, recently the structured changed in the example. Issue, volume, pages are now qualifiers of the publication title:

![wikidata-structure](https://user-images.githubusercontent.com/5199995/28251968-99f52bfe-6a89-11e7-95d4-39fe0a38e23d.jpg)

@pigsonthewing Should this be changed back in Wikidata? (The changes where made by another WikiCite participant, and look intentially, also I could imagine several possible problems with such a nested approach.)

**Comment by pigsonthewing** [comment]
There is a dispute over how best to do this. I would argue that the use of sub-properties as shown in your image is optimal because a paper can be published in more than one venue. 

Since Zotero cannot write sub-properties (because it does not know the QID of item for the journal), it should continue to write such values as top-level statements. A human (or bot) can alter move them.

**Comment by zuphilip** [comment]
Do you have a link to this discussion (or is this spread over several discussions)?

**Comment by pigsonthewing** [comment]
Several discussions; most not very civil.
